import logging

from ansible_base.activitystream.models import AuditableModel
from ansible_base.authentication.authenticator_plugins.utils import get_authenticator_plugin
from ansible_base.authentication.models import Authenticator
from ansible_base.authentication.utils.authentication import determine_username_from_uid
from ansible_base.lib.abstract_models.common import CommonModel
from ansible_base.lib.abstract_models.user import AbstractDABUser
from ansible_base.lib.utils.models import is_system_user, user_summary_fields
from ansible_base.resource_registry.fields import AnsibleResourceField
from ansible_base.resource_registry.models.service_identifier import service_id
from django.contrib.auth.hashers import UNUSABLE_PASSWORD_PREFIX, UNUSABLE_PASSWORD_SUFFIX_LENGTH, get_hashers_by_algorithm, identify_hasher, make_password
from django.db import models
from django.utils.translation import gettext as _

from aap_gateway_api.managers.user import UserUnmanagedManager

logger = logging.getLogger('aap.gateway.models.user')


def password_is_hashed(password):
    """
    Returns a boolean of whether password is hashed with loaded algorithms
    """
    if password is None:
        return False
    try:
        hasher = identify_hasher(password)
    except ValueError:
        # hasher can't be identified or is not loaded
        return False
    return hasher.algorithm in get_hashers_by_algorithm().keys()


def password_is_usable(password):
    """
    Returns True if password is None or wasn't generated by django.contrib.auth.hashers.make_password(None)
    """
    unusable_password_len = len(UNUSABLE_PASSWORD_PREFIX) + UNUSABLE_PASSWORD_SUFFIX_LENGTH

    # what are the odds that a user password starts with unusable prefix and the same length :-?
    return password is None or not (password.startswith(UNUSABLE_PASSWORD_PREFIX) and len(password) == unusable_password_len)


class User(AbstractDABUser, CommonModel, AuditableModel):
    # Enable audit log for this model
    audit_log_enabled = True

    # Gateway enforces email-change policy in its own serializer
    # (_validate_email_change) and in GetOrCreateProcessor for
    # reverse-sync.  The ORM-level pre_save signal must be
    # disabled because Gateway's SSO authentication pipeline
    # updates user emails via direct ORM saves where CRUM has no
    # requesting user set (mid-authentication), which would
    # conflict with the signal's permission checks.
    EMAIL_ENFORCEMENT_VIA_SERIALIZER = True

    ignore_relations = [
        'groups',  # not using the auth app stuff, see Team model
        'user_permissions',  # not using auth app permissions
        'logentry',  # used for Django admin pages, not the API
        'social_auth',  # Social auth endpoint
        'organizations_administered',  # We are going to merge [teams|orgs] the user is an admin in with [teams|orgs] the user is a member of
        'teams_administered',
        'authenticator_users',  # private model .This is not a model we want on the user endpoint. We actually pull this information up into the user payload
        'original_accounts',  # MigratedUserMetadata - accessed through other means
        'role_assignments',  # RBAC role assignments - accessed through RBAC endpoints
        'has_roles',  # RBAC roles - accessed through RBAC endpoints
        'access_tokens',  # OAuth2 access tokens - accessed through OAuth2 endpoints
        'applications',  # OAuth2 applications - accessed through OAuth2 endpoints
        'dab_oauth2_provider_oauth2idtoken',  # OAuth2 ID tokens - accessed through OAuth2 endpoints
        'dab_oauth2_provider_oauth2refreshtoken',  # OAuth2 refresh tokens - accessed through OAuth2 endpoints
        'oauth2_provider_grant',  # OAuth2 grants - accessed through OAuth2 endpoints
    ]
    activity_stream_excluded_field_names = ['last_login', 'last_login_from']

    encrypted_fields = ()  # handed as special case by UserSerializer
    PASSWORD_FIELDS = ["password"]  # Mark password fields so ansible_base.lib.rest_filters can properly block attempts to filter over password

    resource = AnsibleResourceField(primary_key_field="id")

    managed = models.BooleanField(
        editable=False,
        blank=False,
        default=False,
        help_text=_("Indicates if this user is managed by the system. It cannot be modified once created."),
    )

    use_controller_password = models.BooleanField(
        editable=False,
        blank=True,
        default=False,
        help_text=_("Indicates if this user's password is managed by Controller. It cannot be modified once created."),
    )

    # By default, skip managed users (use all_objects for all users queryset)
    objects = UserUnmanagedManager()

    last_login_from = models.ForeignKey(
        Authenticator, on_delete=models.SET_NULL, null=True, default=None, editable=False, help_text="The authenticator the user last logged in with"
    )

    def __init__(self, *args, is_platform_auditor=False, **kwargs):
        super().__init__(*args, **kwargs)
        if is_platform_auditor:
            self._is_platform_auditor = True
        # Store the original value of the fields to check for field changes later
        self._original_fields = self._get_fields()

    def _get_fields(self):
        """
        Return a dictionary of the model's instance fields and their current values.
        """
        return {field.name: self.__dict__.get(field.name) for field in self._meta.fields}

    def fetch_platform_auditor_membership(self):
        "Get from the database True or False, this user is a system auditor"
        from aap_gateway_api.utils.rbac import get_platform_auditor_role

        rd = get_platform_auditor_role()
        return self.role_assignments.filter(role_definition=rd).exists()

    def apply_platform_auditor_membership(self, value):
        from aap_gateway_api.utils.rbac import get_platform_auditor_role

        """Change RBAC SystemAuditor role to reflect given value"""
        rd = get_platform_auditor_role()
        prior_value = self.fetch_platform_auditor_membership()
        if bool(prior_value) != bool(value):
            if prior_value:
                self.role_assignments.filter(role_definition=rd).delete()
            else:
                rd.give_global_permission(self)

        self._is_platform_auditor = value

    def save(self, *args, **kwargs):
        is_new_user = bool(not self.pk)

        # If the password is empty string lets make it None, this will get turned into an unusable password by make_password
        if self.password == '':
            self.password = None

        if password_is_usable(self.password) and not password_is_hashed(self.password):
            self.password = make_password(self.password)

        # Verify if the user's information has been updated for existing and unmanaged users.
        # If yes, invalidated jwt cache
        if not is_new_user and not self.managed:
            fields = ["username", "first_name", "last_name", "email", "is_superuser"]
            fields_changed = any(self._original_fields[field] != getattr(self, field) for field in fields)

            if fields_changed:
                from aap_gateway_api.utils.jwt_cache import invalidate_cached_jwt

                invalidate_cached_jwt(self)

        super().save(*args, **kwargs)

        # If the system auditor role was set on unsaved object, apply it now that it is saved
        if is_new_user and hasattr(self, '_is_platform_auditor'):
            self.apply_platform_auditor_membership(self._is_platform_auditor)

    def delete(self, *args, **kwargs):
        # Prevent the system user from ever being deleted
        if is_system_user(self):
            raise ValueError("The system user cannot be deleted")
        super().delete(*args, **kwargs)

    def logout(self):
        logger.debug(f"Logging out user {self.username} from any active backends")
        # cookies = Cookie.objects.filter(user=self)
        # for cookie in cookies:
        #    cookie.logout()

    def summary_fields(self):
        return user_summary_fields(self)

    def get_authenticator_ids(self) -> list[int]:
        return list(self.authenticator_users.values_list('provider__id', flat=True))

    def get_authenticator_uids(self) -> list[str]:
        return list(self.authenticator_users.values_list('uid', flat=True).distinct())

    def get_associated_authenticators(self) -> dict:
        return {
            auth_user['provider__id']: {"uid": auth_user['uid'], **({"email": auth_user['email']} if auth_user['email'] not in [None, ''] else {})}
            for auth_user in self.authenticator_users.values('provider__id', 'uid', 'email')
        }

    def get_is_platform_auditor(self):
        if not hasattr(self, '_is_platform_auditor'):
            # Prefer the queryset annotation (set by UserViewSet.get_queryset on list views)
            # to avoid a per-object .exists() query during serialization.
            if hasattr(self, '_annotated_is_platform_auditor'):
                self._is_platform_auditor = self._annotated_is_platform_auditor
            else:
                self._is_platform_auditor = self.fetch_platform_auditor_membership()
        return self._is_platform_auditor

    def set_is_platform_auditor(self, value):
        if not self.pk:
            # For unsaved objects, delay application of membership, used in save method
            self._is_platform_auditor = value
            return

        if (not hasattr(self, '_is_platform_auditor')) or bool(self._is_platform_auditor) != bool(value):
            self.apply_platform_auditor_membership(value)

    def del_is_platform_auditor(self):
        if hasattr(self, '_is_platform_auditor'):
            del self._is_platform_auditor

    is_platform_auditor = property(get_is_platform_auditor, set_is_platform_auditor, del_is_platform_auditor)

    @property
    def organizations(self):
        from aap_gateway_api.models import Organization

        return Organization.access_qs(self, 'member')

    @property
    def is_system_auditor(self):
        """Temporary shim to satisfy ansible_base.lib.utils.views.permissions.IsSuperuserOrAuditor"""
        return self.is_platform_auditor

    @property
    def is_migrated(self):
        return str(self.resource.service_id) == str(service_id())

    def update_local_authenticator_uid_from_username(self):
        """
        Ensure local authenticator(s) attached to the user have a uid corresponding
        to the username.
        """
        for authenticator_user in self.authenticator_users.all():
            auth_type = get_authenticator_plugin(authenticator_user.provider.type).type
            if auth_type == 'local':
                username = determine_username_from_uid(uid=self.username, email=authenticator_user.email, authenticator=authenticator_user.provider)
                authenticator_user.uid = username
                authenticator_user.save()


class MigratedUserMetadata(CommonModel):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="original_accounts", help_text=_("The gateway user this migrated user is associated with.")
    )
    service = models.ForeignKey("ServiceCluster", on_delete=models.CASCADE, help_text=_("The service cluster this user was migrated from."))
    original_username = models.CharField(max_length=255, help_text=_("The original username used by the service cluster for this user."))
    backend_classification = models.CharField(
        max_length=255, null=True, default=None, help_text=_("The category of authentication the user used in the service cluster.")
    )

    class Meta:
        unique_together = [('user', 'service')]
